name: Generate QR Code

on:
  push:
    paths: [.github/workflows/generate.yml]
  workflow_dispatch:
  schedule:
    #        ┌──────────────── minute (0 - 59)
    #        │ ┌────────────── hour (0 - 23)
    #        │ │ ┌──────────── day of the month (1 - 31)
    #        │ │ │ ┌────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌──────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '0 0 * * MON-FRI'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      HOST_URL: ${{ secrets.HOST_URL }}
      HOST_EMAIL: ${{ secrets.HOST_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.7.0

      - name: Set Git config
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Generate QR code
        run: |
          sed -i "$(grep -n -m 1 'Go to previous QR Code' README.md | cut -d: -f1)s,/tree/[^\"]*,/tree/$(git rev-parse HEAD)#$REPOSITORY_NAME," README.md
          curl -s -L https://github.com/winstxnhdw/$REPOSITORY_NAME/releases/download/latest/index.js | node
          git add resources/qr_code.svg README.md
          git commit -m "chore(resources): update QR code"
          git push
