name: Generate QR Code

on:
  workflow_dispatch:
  schedule:
    #        ┌──────────────── minute (0 - 59)
    #        │ ┌────────────── hour (0 - 23)
    #        │ │    ┌───────── day of the month (1 - 31)
    #        │ │    │ ┌─────── month (1 - 12 or JAN-DEC)
    #        │ │    │ │ ┌───── day of the week (0 - 6 or SUN-SAT)
    #        │ │    │ │ │
    #        │ │    │ │ │
    #        │ │    │ │ │
    #        * *    * * *
    - cron: '0 0-12 * * MON-FRI'

jobs:
  Generate:
    runs-on: ubuntu-latest
    env:
      HOST_URL: ${{ secrets.HOST_URL }}
      HOST_EMAIL: ${{ secrets.HOST_EMAIL }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Generate QR code
        run: curl -s -L https://github.com/winstxnhdw/yz-visitor-pass/releases/download/latest/index.js | node

      - name: Push changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add resources/qr_code.svg
          git commit -m "chore(resources): update QR code" || exit 0
          git push
