name: Deploy

on:
  push:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/main.yml
      - package.json
      - tsconfig.json

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Deploy
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: latest
          RELEASE_TITLE: Build
          RELEASE_ASSET: dist/index.js
        run: |
          gh release delete ${{ env.RELEASE_TAG }} -y || true
          gh release create ${{ env.RELEASE_TAG }} -t '${{ env.RELEASE_TITLE }}' || true
          gh release upload ${{ env.RELEASE_TAG }} ${{ env.RELEASE_ASSET }} --clobber
